[manifest]
version = "0.0.1"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "function Game:update_game_over(dt)"
position = "after"
payload = """
if true then
	G.GAME.daily_active = false
	G.GAME.daily_complete = true
	print(G.GAME.daily_active, G.GAME.daily_complete)
	G.FUNCS.upload_score()
end
"""
overwrite = false
match_indent = true
